/**
 * Bristol Study Spots Database
 * Total locations: 100
 */

import type { Location } from './locations';

export const bristolLocations: Location[] = [
  {
    "id": 1,
    "name": "Boston Tea Party Stokes Croft",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "75 Stokes Croft, Bristol BS1 3RD",
    "lat": 51.4609,
    "lng": -2.5893,
    "website": "https://bostonteaparty.co.uk",
    "atmosphere": "Spacious industrial-chic cafe with exposed brick, large communal tables, and a buzzy creative vibe. Popular with students and freelancers.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "popular",
      "spacious",
      "brunch"
    ],
    "openingHours": "Mon-Sat 7am-7pm, Sun 8am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 2,
    "name": "Society Cafe Farr's Lane",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Harbourside",
    "address": "Farr's Lane, Narrow Quay, Bristol BS1 4BH",
    "lat": 51.4507,
    "lng": -2.5976,
    "website": "https://www.society-cafe.com",
    "atmosphere": "Minimalist Scandi-inspired cafe overlooking the harbour. Clean lines, natural light, and excellent specialty coffee.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "aesthetic",
      "specialty coffee",
      "harbour views"
    ],
    "openingHours": "Mon-Fri 7:30am-5:30pm, Sat-Sun 8:30am-5:30pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Saturday mornings",
    "studyScore": 8.8,
    "image": ""
  },
  {
    "id": 3,
    "name": "Full Court Press",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Old City",
    "address": "59 Broad Street, Bristol BS1 2EJ",
    "lat": 51.4543,
    "lng": -2.5952,
    "website": "https://www.fullcourtpress.coffee",
    "atmosphere": "Award-winning specialty coffee shop in a beautiful old building. Intimate space with excellent pour-overs and a focused atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "small",
    "tags": [
      "specialty coffee",
      "award-winning",
      "intimate"
    ],
    "openingHours": "Mon-Fri 7:30am-5pm, Sat 9am-5pm, Sun 10am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 4,
    "name": "Watershed Cafe & Bar",
    "type": "Quiet Study Cafe",
    "category": "Creative Workspace",
    "neighborhood": "Harbourside",
    "address": "1 Canon's Road, Bristol BS1 5TX",
    "lat": 51.4499,
    "lng": -2.5988,
    "website": "https://www.watershed.co.uk",
    "atmosphere": "Cultural hub cafe inside Bristol's renowned cinema and media centre. Waterfront views, creative energy, and a relaxed daytime atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "cultural",
      "waterfront",
      "creative"
    ],
    "openingHours": "Mon-Sat 9:30am-11pm, Sun 10am-10:30pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 5,
    "name": "Hotplate",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "104 Stokes Croft, Bristol BS1 3RU",
    "lat": 51.4617,
    "lng": -2.5891,
    "website": "",
    "atmosphere": "Bright and airy cafe with a focus on brunch and specialty coffee. Large windows flood the space with natural light.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "bright",
      "brunch",
      "natural light"
    ],
    "openingHours": "Mon-Fri 8am-4pm, Sat-Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 8.6,
    "image": ""
  },
  {
    "id": 6,
    "name": "Love Bristol Cafe",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Park Street",
    "address": "20 Park Street, Bristol BS1 5JA",
    "lat": 51.4541,
    "lng": -2.6019,
    "website": "",
    "atmosphere": "Cozy cafe on Bristol's iconic Park Street. Popular with university students, offering good coffee and a warm atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "student-friendly",
      "central",
      "cozy"
    ],
    "openingHours": "Mon-Sat 8am-7:30pm, Sun 9am-6pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.2,
    "image": ""
  },
  {
    "id": 7,
    "name": "Coffee #1 Clifton",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Clifton",
    "address": "3 Princess Victoria Street, Bristol BS8 4BP",
    "lat": 51.4555,
    "lng": -2.6172,
    "website": "https://www.coffee1.co.uk",
    "atmosphere": "Charming cafe in the heart of Clifton Village. Comfortable seating, reliable Wi-Fi, and a steady stream of students.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "clifton",
      "reliable",
      "comfortable"
    ],
    "openingHours": "Mon-Sat 7:30am-6pm, Sun 8:30am-5:30pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Saturday afternoon",
    "studyScore": 8.3,
    "image": ""
  },
  {
    "id": 8,
    "name": "Hatter House Cafe",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Old City",
    "address": "9 Clare Street, Bristol BS1 1XA",
    "lat": 51.4536,
    "lng": -2.5936,
    "website": "",
    "atmosphere": "Alice in Wonderland-themed cafe with quirky decor, excellent cakes, and a whimsical atmosphere. Surprisingly good for focused work.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "quirky",
      "themed",
      "cakes"
    ],
    "openingHours": "Mon-Sat 8am-7:30pm, Sun 9am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend afternoons",
    "studyScore": 7.9,
    "image": ""
  },
  {
    "id": 9,
    "name": "Spicer & Cole",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Old City",
    "address": "1 Queen Square Avenue, Bristol BS1 4JA",
    "lat": 51.4516,
    "lng": -2.5964,
    "website": "https://spicerandcole.co.uk",
    "atmosphere": "Artisan bakery-cafe overlooking Queen Square. Fresh pastries, sourdough bread, and excellent flat whites in a bright, airy space.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "bakery",
      "artisan",
      "queen square"
    ],
    "openingHours": "Mon-Fri 7:30am-5pm, Sat 8am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Early mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.1,
    "image": ""
  },
  {
    "id": 10,
    "name": "The Canteen",
    "type": "Quiet Study Cafe",
    "category": "Creative Workspace",
    "neighborhood": "Stokes Croft",
    "address": "80 Stokes Croft, Bristol BS1 3QY",
    "lat": 51.4605,
    "lng": -2.589,
    "website": "https://canteen.co.uk",
    "atmosphere": "Community-focused cafe and bar in the heart of Stokes Croft. Eclectic decor, local art on walls, and a creative atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "community",
      "creative",
      "art"
    ],
    "openingHours": "Mon-Thu 10am-12am, Fri-Sat 10am-1am, Sun 10am-11pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 11,
    "name": "Brew Coffee Co",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Whiteladies Road",
    "address": "45 Whiteladies Road, Bristol BS8 2LS",
    "lat": 51.4625,
    "lng": -2.6105,
    "website": "",
    "atmosphere": "Popular student cafe on Whiteladies Road. Spacious interior with plenty of seating and a relaxed study vibe.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "high",
    "tableSize": "medium",
    "tags": [
      "student-friendly",
      "spacious",
      "whiteladies"
    ],
    "openingHours": "Mon-Fri 7:30am-6pm, Sat-Sun 8am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.6,
    "image": ""
  },
  {
    "id": 12,
    "name": "Mrs. Potts Chocolate House",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Park Street",
    "address": "50 Park Street, Bristol BS1 5JG",
    "lat": 51.4548,
    "lng": -2.6025,
    "website": "https://mrspottschocolatehouse.co.uk",
    "atmosphere": "Enchanting chocolate house with rich hot chocolates and decadent cakes. Cozy nooks perfect for reading and quiet study.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "warm",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "small",
    "tags": [
      "chocolate",
      "cozy",
      "nooks"
    ],
    "openingHours": "Mon-Sat 10am-8pm, Sun 11am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Weekend afternoons",
    "studyScore": 7.7,
    "image": ""
  },
  {
    "id": 13,
    "name": "Illustrate",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Park Street",
    "address": "79 Park Street, Bristol BS1 5PF",
    "lat": 51.4553,
    "lng": -2.603,
    "website": "",
    "atmosphere": "Stylish cafe with a focus on brunch and specialty drinks. Modern interior with Instagram-worthy presentation.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "stylish",
      "brunch",
      "instagram"
    ],
    "openingHours": "Mon-Sun 10am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 14,
    "name": "Folk House Cafe",
    "type": "Quiet Study Cafe",
    "category": "Creative Workspace",
    "neighborhood": "Park Street",
    "address": "40A Park Street, Bristol BS1 5JG",
    "lat": 51.4545,
    "lng": -2.6022,
    "website": "https://www.folkhouse.co.uk",
    "atmosphere": "Hidden gem inside a community arts centre. Peaceful courtyard garden, creative classes upstairs, and a wonderfully calm atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "hidden gem",
      "garden",
      "arts centre"
    ],
    "openingHours": "Mon-Sat 9am-8:30pm, Sun closed",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Class times",
    "studyScore": 9.0,
    "image": ""
  },
  {
    "id": 15,
    "name": "Cafe Kino",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "108 Stokes Croft, Bristol BS1 3RU",
    "lat": 51.4619,
    "lng": -2.5892,
    "website": "https://www.cafekino.coop",
    "atmosphere": "Worker-owned cooperative cafe with vegan food and strong community values. Relaxed, unpretentious atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "vegan",
      "cooperative",
      "community"
    ],
    "openingHours": "Mon-Sat 10am-10pm, Sun 10am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.2,
    "image": ""
  },
  {
    "id": 16,
    "name": "Pinkmans",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Park Street",
    "address": "85 Park Street, Bristol BS1 5PJ",
    "lat": 51.4555,
    "lng": -2.6032,
    "website": "https://pinkmans.co.uk",
    "atmosphere": "Artisan bakery with incredible sourdough and pastries. Industrial-chic interior with communal tables.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "bakery",
      "sourdough",
      "artisan"
    ],
    "openingHours": "Mon-Sat 8am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.4,
    "image": ""
  },
  {
    "id": 17,
    "name": "Mokoko Bakery",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Wapping Wharf",
    "address": "Wapping Wharf, Bristol BS1 6UD",
    "lat": 51.4465,
    "lng": -2.5985,
    "website": "https://www.mokoko.co.uk",
    "atmosphere": "Waterfront bakery with stunning harbour views. Fresh pastries, excellent coffee, and a bright modern space.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "small",
    "tags": [
      "waterfront",
      "bakery",
      "views"
    ],
    "openingHours": "Mon-Fri 8am-4pm, Sat-Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.9,
    "image": ""
  },
  {
    "id": 18,
    "name": "Wayland's Yard",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Whiteladies Road",
    "address": "45 Whiteladies Road, Bristol BS8 2LS",
    "lat": 51.4623,
    "lng": -2.6108,
    "website": "https://waylandsyard.com",
    "atmosphere": "Popular specialty coffee shop with a bright, modern interior. Known for excellent flat whites and a student-friendly atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "high",
    "tableSize": "medium",
    "tags": [
      "specialty coffee",
      "modern",
      "student-friendly"
    ],
    "openingHours": "Mon-Fri 7:30am-5pm, Sat-Sun 8:30am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 19,
    "name": "The Crafty Egg Stokes Croft",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "95 Stokes Croft, Bristol BS1 3RD",
    "lat": 51.4612,
    "lng": -2.5891,
    "website": "https://www.thecraftyegg.co.uk",
    "atmosphere": "Brunch-focused cafe with a relaxed vibe. Good for morning study sessions before the brunch crowd arrives.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "brunch",
      "relaxed",
      "morning"
    ],
    "openingHours": "Mon-Sun 8:30am-10pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Early mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.2,
    "image": ""
  },
  {
    "id": 20,
    "name": "Tobacco Factory Theatres Cafe",
    "type": "Quiet Study Cafe",
    "category": "Creative Workspace",
    "neighborhood": "Southville",
    "address": "Raleigh Road, Southville, Bristol BS3 1TF",
    "lat": 51.443,
    "lng": -2.6015,
    "website": "https://tobaccofactorytheatres.com",
    "atmosphere": "Arts venue cafe in a converted tobacco factory. High ceilings, creative energy, and a wonderful community feel.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "arts venue",
      "converted factory",
      "community"
    ],
    "openingHours": "Mon-Sat 10am-11pm, Sun 10am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday daytime",
    "peakBusyTimes": "Show nights",
    "studyScore": 8.3,
    "image": ""
  },
  {
    "id": 21,
    "name": "Bocabar",
    "type": "Quiet Study Cafe",
    "category": "Creative Workspace",
    "neighborhood": "Brislington",
    "address": "Unit 1, Paintworks, Bath Road, Bristol BS4 3EH",
    "lat": 51.4425,
    "lng": -2.5755,
    "website": "https://bocabar.co.uk",
    "atmosphere": "Vibrant cafe-bar in the Paintworks creative quarter. Industrial chic with local art, great pizza, and a creative community.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "creative quarter",
      "art",
      "pizza"
    ],
    "openingHours": "Mon-Thu 10am-11pm, Fri-Sat 10am-12am, Sun 10am-10pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 7.6,
    "image": ""
  },
  {
    "id": 22,
    "name": "Playground Coffee House",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Old City",
    "address": "45 Saint Nicholas Street, Bristol BS1 1TP",
    "lat": 51.453,
    "lng": -2.594,
    "website": "",
    "atmosphere": "Cozy independent coffee house with board games and a relaxed atmosphere. Great for casual study sessions.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "board games",
      "cozy",
      "independent"
    ],
    "openingHours": "Mon-Sat 8am-10:45pm, Sun 10am-6pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Evenings",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 23,
    "name": "Friska Glass Wharf",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Temple Quarter",
    "address": "Glass Wharf, Temple Quay, Bristol BS2 0EL",
    "lat": 51.4515,
    "lng": -2.584,
    "website": "https://friskafood.com",
    "atmosphere": "Modern cafe in the Temple Quarter business district. Clean, bright interior with good food and reliable Wi-Fi.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "business district",
      "modern",
      "healthy"
    ],
    "openingHours": "Mon-Fri 7am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 24,
    "name": "The Bristol Loaf Bedminster",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Bedminster",
    "address": "96 Bedminster Parade, Bristol BS3 4HL",
    "lat": 51.441,
    "lng": -2.5945,
    "website": "https://thebristolloaf.co.uk",
    "atmosphere": "Artisan bakery with incredible sourdough and pastries. Warm, welcoming space with wooden tables and the smell of fresh bread.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "bakery",
      "sourdough",
      "warm"
    ],
    "openingHours": "Mon-Sat 8am-6pm, Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 25,
    "name": "Coffee Under Pressure",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Redland",
    "address": "134 Whiteladies Road, Bristol BS8 2RS",
    "lat": 51.4658,
    "lng": -2.6118,
    "website": "",
    "atmosphere": "Tiny specialty coffee shop with exceptional espresso. Limited seating but a focused, quiet atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "specialty",
      "espresso",
      "quiet"
    ],
    "openingHours": "Mon-Fri 7:30am-4pm, Sat 8:30am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Morning rush",
    "studyScore": 7.0,
    "image": ""
  },
  {
    "id": 26,
    "name": "Mocha Mocha",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Cotham",
    "address": "40 Saint Michael's Hill, Bristol BS2 8DX",
    "lat": 51.4575,
    "lng": -2.6005,
    "website": "",
    "atmosphere": "Beloved student cafe near the university. Generous portions, affordable prices, and a warm community feel.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "high",
    "tableSize": "medium",
    "tags": [
      "student favourite",
      "affordable",
      "generous portions"
    ],
    "openingHours": "Mon-Fri 7:45am-5pm, Sat 8:30am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Early mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 27,
    "name": "The Arnolfini Cafe",
    "type": "Quiet Study Cafe",
    "category": "Museum/Gallery Cafe",
    "neighborhood": "Harbourside",
    "address": "16 Narrow Quay, Bristol BS1 4QA",
    "lat": 51.4497,
    "lng": -2.5975,
    "website": "https://www.arnolfini.org.uk",
    "atmosphere": "Contemporary arts centre cafe with harbour views. Minimalist space with rotating exhibitions and a thoughtful atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "gallery",
      "harbour views",
      "minimalist"
    ],
    "openingHours": "Tue-Sun 11am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Exhibition openings",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 28,
    "name": "Primrose Cafe",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Clifton",
    "address": "1 Boyces Avenue, Clifton, Bristol BS8 4AA",
    "lat": 51.4558,
    "lng": -2.6148,
    "website": "https://www.primrosecafe.co.uk",
    "atmosphere": "Charming neighbourhood cafe in Clifton Village. Beautiful terrace, excellent brunch, and a refined atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "clifton village",
      "terrace",
      "refined"
    ],
    "openingHours": "Mon-Sat 9am-4pm, Sun 10am-3pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 29,
    "name": "The Old Bookshop",
    "type": "Quiet Study Cafe",
    "category": "Bookstore Cafe",
    "neighborhood": "Southville",
    "address": "65 North Street, Southville, Bristol BS3 1ES",
    "lat": 51.4432,
    "lng": -2.602,
    "website": "",
    "atmosphere": "Quirky bar-cafe in a former bookshop. Eclectic decor, board games, and a bohemian atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "warm",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "quirky",
      "bookshop",
      "bohemian"
    ],
    "openingHours": "Mon-Thu 11am-11pm, Fri-Sat 11am-12am, Sun 11am-10pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Evenings",
    "studyScore": 7.3,
    "image": ""
  },
  {
    "id": 30,
    "name": "Spoke & Stringer",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Harbourside",
    "address": "Clifton Down Shopping Centre, Whiteladies Road, Bristol BS8 2NN",
    "lat": 51.464,
    "lng": -2.613,
    "website": "https://spokeandstringer.com",
    "atmosphere": "Cycling-themed cafe with excellent brunch and coffee. Bright, spacious interior with a friendly community vibe.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "cycling",
      "brunch",
      "spacious"
    ],
    "openingHours": "Mon-Fri 8am-7pm, Sat-Sun 9am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.7,
    "image": ""
  },
  {
    "id": 31,
    "name": "Little Victories",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Harbourside",
    "address": "7 Gaol Ferry Steps, Bristol BS1 6WE",
    "lat": 51.4478,
    "lng": -2.598,
    "website": "https://littlevictoriescoffee.co.uk",
    "atmosphere": "Specialty coffee shop with a focus on quality. Small but perfectly formed, with harbour views and excellent pour-overs.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "specialty",
      "harbour",
      "quality"
    ],
    "openingHours": "Mon-Fri 8am-5pm, Sat-Sun 9am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Morning rush",
    "studyScore": 7.2,
    "image": ""
  },
  {
    "id": 32,
    "name": "N\u00b012 Easton",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Easton",
    "address": "12 High Street, Easton, Bristol BS5 6DN",
    "lat": 51.458,
    "lng": -2.569,
    "website": "",
    "atmosphere": "Hidden gem in multicultural Easton. Relaxed community cafe with affordable prices and a warm welcome.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "hidden gem",
      "community",
      "affordable"
    ],
    "openingHours": "Mon-Sat 8am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.4,
    "image": ""
  },
  {
    "id": 33,
    "name": "25A Old Market",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Old Market",
    "address": "25A Old Market Street, Bristol BS2 0HB",
    "lat": 51.4545,
    "lng": -2.587,
    "website": "",
    "atmosphere": "Tiny independent cafe in Old Market. Excellent coffee, homemade cakes, and a genuinely friendly atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "independent",
      "homemade",
      "friendly"
    ],
    "openingHours": "Mon-Fri 8am-3:30pm, Sat 9am-3pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Morning rush",
    "studyScore": 8.3,
    "image": ""
  },
  {
    "id": 34,
    "name": "FED 313",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Gloucester Road",
    "address": "313 Gloucester Road, Bristol BS7 8PE",
    "lat": 51.473,
    "lng": -2.592,
    "website": "",
    "atmosphere": "Popular brunch spot on Gloucester Road. Bright, modern interior with a relaxed atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "brunch",
      "gloucester road",
      "modern"
    ],
    "openingHours": "Mon-Fri 8:30am-4pm, Sat-Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.4,
    "image": ""
  },
  {
    "id": 35,
    "name": "The Cloakroom Cafe",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Clifton",
    "address": "Clifton Down Station, Whiteladies Road, Bristol BS8 2PN",
    "lat": 51.4645,
    "lng": -2.6125,
    "website": "",
    "atmosphere": "Charming cafe in a converted Victorian railway station cloakroom. Unique setting with original features and cozy atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "warm",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "victorian",
      "railway",
      "unique"
    ],
    "openingHours": "Mon-Fri 8am-4pm, Sat 9am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Morning rush",
    "studyScore": 8.6,
    "image": ""
  },
  {
    "id": 36,
    "name": "Workhouse Cafe",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "101 Stokes Croft, Bristol BS1 3RD",
    "lat": 51.4613,
    "lng": -2.5892,
    "website": "",
    "atmosphere": "No-frills community cafe with generous portions and affordable prices. Popular with students and locals alike.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "affordable",
      "generous",
      "community"
    ],
    "openingHours": "Mon-Sat 9am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 37,
    "name": "Poco",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "45 Jamaica Street, Bristol BS2 8JP",
    "lat": 51.46,
    "lng": -2.5885,
    "website": "https://www.pocotapasbar.com",
    "atmosphere": "Tapas bar and cafe with a focus on sustainability. Daytime is quiet and perfect for study.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "sustainable",
      "tapas",
      "quiet daytime"
    ],
    "openingHours": "Mon-Sat 12pm-10pm, Sun 12pm-9pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Early afternoon",
    "peakBusyTimes": "Dinner time",
    "studyScore": 7.0,
    "image": ""
  },
  {
    "id": 38,
    "name": "East Village Cafe",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Easton",
    "address": "231 Church Road, Easton, Bristol BS5 9HL",
    "lat": 51.4575,
    "lng": -2.5665,
    "website": "",
    "atmosphere": "Friendly neighbourhood cafe in Easton with a diverse community feel. Good coffee and homemade food.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "neighbourhood",
      "diverse",
      "homemade"
    ],
    "openingHours": "Mon-Sat 8am-4pm, Sun 9am-3pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 39,
    "name": "Bakesmiths",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Clifton",
    "address": "1 Regent Street, Clifton, Bristol BS8 4HW",
    "lat": 51.456,
    "lng": -2.6155,
    "website": "https://bakesmiths.co.uk",
    "atmosphere": "Premium bakery-cafe in Clifton with outstanding pastries and bread. Bright, modern space with a refined atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "premium bakery",
      "clifton",
      "refined"
    ],
    "openingHours": "Mon-Sat 8am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 7.6,
    "image": ""
  },
  {
    "id": 40,
    "name": "Flour House",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Gloucester Road",
    "address": "291 Gloucester Road, Bristol BS7 8NY",
    "lat": 51.4725,
    "lng": -2.5918,
    "website": "",
    "atmosphere": "Artisan bakery with incredible croissants and sourdough. Small but charming space on Gloucester Road.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "limited",
    "crowdLevel": "medium",
    "tableSize": "small",
    "tags": [
      "artisan",
      "croissants",
      "charming"
    ],
    "openingHours": "Tue-Sat 8am-3pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 6.8,
    "image": ""
  },
  {
    "id": 41,
    "name": "Coffee + Beer",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Cotham",
    "address": "Cotham Hill, Bristol BS6 6JY",
    "lat": 51.4595,
    "lng": -2.6025,
    "website": "",
    "atmosphere": "Dual-concept cafe serving specialty coffee by day and craft beer by evening. Modern, minimalist interior.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "dual concept",
      "specialty",
      "minimalist"
    ],
    "openingHours": "Mon-Fri 8am-10pm, Sat-Sun 9am-10pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 42,
    "name": "Monty Carlos",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Easton",
    "address": "Mivart Street, Easton, Bristol BS5 6JF",
    "lat": 51.4582,
    "lng": -2.57,
    "website": "",
    "atmosphere": "Hidden gem in Easton with a Mediterranean feel. Courtyard garden, homemade food, and a wonderfully relaxed atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "garden",
      "mediterranean",
      "relaxed"
    ],
    "openingHours": "Mon-Sat 9am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 43,
    "name": "The Red Church",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Redfield",
    "address": "Church Road, Redfield, Bristol BS5 9JA",
    "lat": 51.451,
    "lng": -2.565,
    "website": "",
    "atmosphere": "Converted church turned community cafe. Stunning architecture, high ceilings, and a peaceful atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "converted church",
      "stunning",
      "peaceful"
    ],
    "openingHours": "Mon-Fri 9am-4pm, Sat 10am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.8,
    "image": ""
  },
  {
    "id": 44,
    "name": "Catley's",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Redland",
    "address": "Chandos Road, Redland, Bristol BS6 6PG",
    "lat": 51.465,
    "lng": -2.605,
    "website": "",
    "atmosphere": "Neighbourhood cafe in leafy Redland. Popular with families and students, offering good coffee and homemade cakes.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "neighbourhood",
      "redland",
      "homemade"
    ],
    "openingHours": "Mon-Sat 8am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 7.7,
    "image": ""
  },
  {
    "id": 45,
    "name": "Peggy's Bristol",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Clifton",
    "address": "The Mall, Clifton, Bristol BS8 4JG",
    "lat": 51.4562,
    "lng": -2.6165,
    "website": "",
    "atmosphere": "Stylish brunch cafe in Clifton with beautiful interiors and Instagram-worthy food presentation.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "stylish",
      "brunch",
      "instagram"
    ],
    "openingHours": "Mon-Sun 9am-5pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.3,
    "image": ""
  },
  {
    "id": 46,
    "name": "1B Pitville",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Redland",
    "address": "1B Pitville Place, Redland, Bristol BS6 5QA",
    "lat": 51.4648,
    "lng": -2.608,
    "website": "",
    "atmosphere": "Tiny hidden cafe in a residential Redland street. Excellent coffee, homemade food, and a genuinely peaceful atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "hidden",
      "peaceful",
      "residential"
    ],
    "openingHours": "Mon-Fri 9am-4pm, Sat 9am-3pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Morning rush",
    "studyScore": 8.7,
    "image": ""
  },
  {
    "id": 47,
    "name": "Coffee #1 Welsh Back",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Old City",
    "address": "51 Welsh Back, Bristol BS1 4SP",
    "lat": 51.451,
    "lng": -2.5935,
    "website": "https://www.coffee1.co.uk",
    "atmosphere": "Waterfront Coffee #1 with views over the floating harbour. Reliable chain with good Wi-Fi and comfortable seating.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "waterfront",
      "reliable",
      "harbour"
    ],
    "openingHours": "Mon-Sat 7:30am-6pm, Sun 8:30am-5:30pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 48,
    "name": "The Bristol Loaf Beacon",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Hotwells",
    "address": "Trenchard Street, Bristol BS1 5AN",
    "lat": 51.453,
    "lng": -2.605,
    "website": "https://thebristolloaf.co.uk",
    "atmosphere": "Second branch of the beloved Bristol Loaf. Same incredible bread and pastries in a central location.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "bakery",
      "central",
      "sourdough"
    ],
    "openingHours": "Mon-Fri 8am-4pm, Sat 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 49,
    "name": "Lounge Southville",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Southville",
    "address": "227-231 North Street, Southville, Bristol BS3 1JD",
    "lat": 51.4435,
    "lng": -2.6025,
    "website": "https://thelounges.co.uk",
    "atmosphere": "Eclectic neighbourhood lounge with mismatched furniture and a relaxed atmosphere. Good for all-day working.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "warm",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "eclectic",
      "all-day",
      "comfortable"
    ],
    "openingHours": "Mon-Thu 9am-11pm, Fri-Sat 9am-12am, Sun 9am-10:30pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 7.4,
    "image": ""
  },
  {
    "id": 50,
    "name": "Ahh Toots",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Totterdown",
    "address": "Wells Road, Totterdown, Bristol BS4 2AG",
    "lat": 51.4395,
    "lng": -2.583,
    "website": "",
    "atmosphere": "Charming vintage-style cafe in Totterdown with homemade cakes and a warm, welcoming atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "warm",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "vintage",
      "homemade",
      "welcoming"
    ],
    "openingHours": "Mon-Sat 9am-5pm, Sun 10am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 7.6,
    "image": ""
  },
  {
    "id": 51,
    "name": "Bristol Central Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "College Green",
    "address": "College Green, Bristol BS1 5TL",
    "lat": 51.453,
    "lng": -2.599,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Stunning Edwardian library with a magnificent domed reading room. One of Bristol's architectural treasures with extensive study facilities.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "historic",
      "dome",
      "reading room"
    ],
    "openingHours": "Mon-Tue 10am-7pm, Wed-Sat 10am-5pm, Sun closed",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "After school",
    "studyScore": 9.2,
    "image": ""
  },
  {
    "id": 52,
    "name": "Clifton Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Clifton",
    "address": "Princess Victoria Street, Clifton, Bristol BS8 4BX",
    "lat": 51.4555,
    "lng": -2.617,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Charming neighbourhood library in the heart of Clifton Village. Quiet study space with good natural light.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "neighbourhood",
      "quiet",
      "clifton"
    ],
    "openingHours": "Mon-Tue 10am-5pm, Wed closed, Thu-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 53,
    "name": "Bedminster Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Bedminster",
    "address": "St Peter's Court, Bedminster Parade, Bristol BS3 4AQ",
    "lat": 51.4408,
    "lng": -2.5942,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Modern community library in Bedminster with study desks and computer access.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "modern",
      "community",
      "computers"
    ],
    "openingHours": "Mon-Tue 10am-5pm, Wed closed, Thu-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 54,
    "name": "Bishopston Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Gloucester Road",
    "address": "Gloucester Road, Bishopston, Bristol BS7 8BN",
    "lat": 51.472,
    "lng": -2.5915,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Community library on Gloucester Road with a friendly atmosphere and good study facilities.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "community",
      "gloucester road",
      "friendly"
    ],
    "openingHours": "Mon-Tue 10am-5pm, Wed closed, Thu-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 55,
    "name": "Henleaze Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Henleaze",
    "address": "Northumbria Drive, Henleaze, Bristol BS9 4HP",
    "lat": 51.481,
    "lng": -2.605,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Quiet suburban library in leafy Henleaze. Peaceful setting with dedicated study areas.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "suburban",
      "peaceful",
      "quiet"
    ],
    "openingHours": "Mon-Tue 10am-5pm, Wed closed, Thu-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 8.2,
    "image": ""
  },
  {
    "id": 56,
    "name": "Redland Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Redland",
    "address": "Whiteladies Road, Redland, Bristol BS6 6SA",
    "lat": 51.4655,
    "lng": -2.61,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Small but well-loved library in the student area of Redland. Good for quiet study sessions.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "student area",
      "quiet",
      "compact"
    ],
    "openingHours": "Mon 10am-5pm, Tue closed, Wed-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 57,
    "name": "Knowle Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Knowle",
    "address": "Broadwalk Shopping Centre, Knowle, Bristol BS4 2QU",
    "lat": 51.432,
    "lng": -2.575,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Community library in Knowle with computer access and study space.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "community",
      "computers",
      "accessible"
    ],
    "openingHours": "Mon-Tue 10am-5pm, Wed closed, Thu-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 58,
    "name": "Fishponds Library",
    "type": "Library",
    "category": "Library",
    "neighborhood": "Fishponds",
    "address": "Fishponds Road, Fishponds, Bristol BS16 3UH",
    "lat": 51.4715,
    "lng": -2.544,
    "website": "https://www.bristol.gov.uk/libraries",
    "atmosphere": "Spacious community library in Fishponds with dedicated study areas and computer access.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "spacious",
      "community",
      "study areas"
    ],
    "openingHours": "Mon-Tue 10am-5pm, Wed closed, Thu-Sat 10am-5pm",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "After school",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 59,
    "name": "DeskLodge Old Market",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Old Market",
    "address": "1 Old Market, Bristol BS2 0HB",
    "lat": 51.4548,
    "lng": -2.5865,
    "website": "https://desklodge.com",
    "atmosphere": "Premium coworking space in a beautifully converted building. Hot desks, private offices, and excellent facilities.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "premium",
      "converted building",
      "facilities"
    ],
    "openingHours": "Mon-Fri 8am-6pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 9.0,
    "image": ""
  },
  {
    "id": 60,
    "name": "Engine Shed",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Temple Meads",
    "address": "Station Approach, Temple Meads, Bristol BS1 6QH",
    "lat": 51.449,
    "lng": -2.582,
    "website": "https://engine-shed.co.uk",
    "atmosphere": "Enterprise hub next to Temple Meads station in Brunel's original train shed. Stunning industrial architecture with modern facilities.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "enterprise hub",
      "brunel",
      "historic"
    ],
    "openingHours": "Mon-Fri 8:30am-5:30pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Events",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 61,
    "name": "Hamilton House",
    "type": "Coworking Space",
    "category": "Creative Workspace",
    "neighborhood": "Stokes Croft",
    "address": "80 Stokes Croft, Bristol BS1 3QY",
    "lat": 51.4605,
    "lng": -2.589,
    "website": "https://hamiltonhouse.org",
    "atmosphere": "Creative community hub in Stokes Croft. Studios, coworking, events, and a vibrant creative community.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "creative hub",
      "community",
      "studios"
    ],
    "openingHours": "Mon-Fri 9am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Events",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 62,
    "name": "Origin Workspace",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Temple Meads",
    "address": "40 Berkeley Square, Bristol BS8 1HP",
    "lat": 51.4555,
    "lng": -2.6005,
    "website": "https://originworkspace.com",
    "atmosphere": "Professional coworking space in a Georgian townhouse on Berkeley Square. Elegant setting with modern amenities.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "professional",
      "georgian",
      "elegant"
    ],
    "openingHours": "Mon-Fri 8am-6pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 9.0,
    "image": ""
  },
  {
    "id": 63,
    "name": "Runway East Bristol",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Temple Meads",
    "address": "1 Victoria Street, Bristol BS1 6AA",
    "lat": 51.4505,
    "lng": -2.588,
    "website": "https://runwayea.st",
    "atmosphere": "Tech-focused coworking space popular with startups. Modern facilities, fast internet, and a dynamic community.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "tech",
      "startups",
      "dynamic"
    ],
    "openingHours": "24/7 for members",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 64,
    "name": "Spaces Glass Wharf",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Temple Quarter",
    "address": "Glass Wharf, Temple Quay, Bristol BS2 0EL",
    "lat": 51.4518,
    "lng": -2.5842,
    "website": "https://www.spacesworks.com",
    "atmosphere": "Modern coworking in the Temple Quarter business district. Floor-to-ceiling windows with city views.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "modern",
      "city views",
      "business district"
    ],
    "openingHours": "Mon-Fri 8am-6pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 8.8,
    "image": ""
  },
  {
    "id": 65,
    "name": "The Guild",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Park Street",
    "address": "68 Park Street, Bristol BS1 5JX",
    "lat": 51.455,
    "lng": -2.6025,
    "website": "",
    "atmosphere": "Boutique coworking space on Park Street. Small, focused community with a professional atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "boutique",
      "focused",
      "professional"
    ],
    "openingHours": "Mon-Fri 8am-6pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 8.8,
    "image": ""
  },
  {
    "id": 66,
    "name": "Raw Space",
    "type": "Coworking Space",
    "category": "Creative Workspace",
    "neighborhood": "Old Market",
    "address": "Old Market, Bristol BS2 0HB",
    "lat": 51.4546,
    "lng": -2.5862,
    "website": "",
    "atmosphere": "Creative coworking space in Old Market. Raw industrial aesthetic with a focus on creative industries.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "creative",
      "industrial",
      "raw"
    ],
    "openingHours": "Mon-Fri 9am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 8.2,
    "image": ""
  },
  {
    "id": 67,
    "name": "Redbrick House",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Old Market",
    "address": "Old Market, Bristol BS2 0HB",
    "lat": 51.4544,
    "lng": -2.5858,
    "website": "",
    "atmosphere": "Community-focused coworking in a converted warehouse. Affordable hot desks and a supportive community.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "community",
      "warehouse",
      "affordable"
    ],
    "openingHours": "Mon-Fri 9am-6pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 68,
    "name": "Broad Quay House",
    "type": "Coworking Space",
    "category": "Coworking Space",
    "neighborhood": "Harbourside",
    "address": "Broad Quay, Bristol BS1 4DJ",
    "lat": 51.4508,
    "lng": -2.596,
    "website": "",
    "atmosphere": "Professional serviced offices with coworking options overlooking the harbour. Premium location and facilities.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "professional",
      "harbour views",
      "premium"
    ],
    "openingHours": "Mon-Fri 8am-6pm",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Mid-morning",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 69,
    "name": "Hotel du Vin Bristol",
    "type": "Hotel Lounge",
    "category": "Hotel Lounge",
    "neighborhood": "Old City",
    "address": "The Sugar House, Narrow Lewins Mead, Bristol BS1 2NU",
    "lat": 51.4555,
    "lng": -2.5935,
    "website": "https://www.hotelduvin.com/locations/bristol",
    "atmosphere": "Boutique hotel in a converted sugar warehouse. Elegant lounge with leather armchairs and a refined atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "warm",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "boutique",
      "elegant",
      "converted warehouse"
    ],
    "openingHours": "All day",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 8.8,
    "image": ""
  },
  {
    "id": 70,
    "name": "Bristol Harbour Hotel",
    "type": "Hotel Lounge",
    "category": "Hotel Lounge",
    "neighborhood": "Old City",
    "address": "53-55 Corn Street, Bristol BS1 1HT",
    "lat": 51.4535,
    "lng": -2.5945,
    "website": "https://www.harbourhotels.co.uk/bristol",
    "atmosphere": "Luxury hotel in a Grade II listed former bank. Stunning marble lobby and comfortable lounge areas.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "luxury",
      "listed building",
      "marble"
    ],
    "openingHours": "All day",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 9.0,
    "image": ""
  },
  {
    "id": 71,
    "name": "The Bristol Hotel",
    "type": "Hotel Lounge",
    "category": "Hotel Lounge",
    "neighborhood": "Harbourside",
    "address": "Prince Street, Bristol BS1 4QF",
    "lat": 51.4495,
    "lng": -2.597,
    "website": "https://www.doylecollection.com/hotels/the-bristol-hotel",
    "atmosphere": "Waterfront hotel with harbour views. Modern lounge area with floor-to-ceiling windows.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "excellent",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "waterfront",
      "modern",
      "harbour views"
    ],
    "openingHours": "All day",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 72,
    "name": "Mercure Bristol Grand Hotel",
    "type": "Hotel Lounge",
    "category": "Hotel Lounge",
    "neighborhood": "Old City",
    "address": "Broad Street, Bristol BS1 2EL",
    "lat": 51.454,
    "lng": -2.595,
    "website": "https://all.accor.com/hotel/6578/index.en.shtml",
    "atmosphere": "Victorian hotel with a grand lobby and comfortable lounge. Classic British hotel atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "warm",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "victorian",
      "grand",
      "classic"
    ],
    "openingHours": "All day",
    "priceLevel": "\u00a3\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 8.2,
    "image": ""
  },
  {
    "id": 73,
    "name": "Hilton Garden Inn Bristol",
    "type": "Hotel Lounge",
    "category": "Hotel Lounge",
    "neighborhood": "Temple Meads",
    "address": "Temple Way, Bristol BS1 6BF",
    "lat": 51.45,
    "lng": -2.5835,
    "website": "https://www.hilton.com/en/hotels/brsctgi-hilton-garden-inn-bristol-city-centre/",
    "atmosphere": "Modern hotel near Temple Meads with a bright lobby lounge. Good for business travellers and remote workers.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "modern",
      "business",
      "temple meads"
    ],
    "openingHours": "All day",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Check-in time",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 74,
    "name": "Brandon Hill & Cabot Tower",
    "type": "Nature/Greenery",
    "category": "Nature/Greenery",
    "neighborhood": "Park Street",
    "address": "Brandon Hill, Park Street, Bristol BS1 5RR",
    "lat": 51.453,
    "lng": -2.604,
    "website": "",
    "atmosphere": "Bristol's oldest park with stunning views from Cabot Tower. Benches and grassy areas perfect for outdoor study in good weather.",
    "wifi": "no",
    "plugSockets": "no",
    "noiseLevel": 1,
    "lightingQuality": "excellent",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "N/A",
    "tags": [
      "park",
      "views",
      "cabot tower"
    ],
    "openingHours": "Dawn to dusk",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Sunny afternoons",
    "peakBusyTimes": "Weekends",
    "studyScore": 7.0,
    "image": ""
  },
  {
    "id": 75,
    "name": "Castle Park",
    "type": "Nature/Greenery",
    "category": "Nature/Greenery",
    "neighborhood": "Old City",
    "address": "Castle Park, Bristol BS1 3XB",
    "lat": 51.4535,
    "lng": -2.591,
    "website": "",
    "atmosphere": "Central park with ruins of St Peter's Church. Peaceful green space in the heart of the city.",
    "wifi": "no",
    "plugSockets": "no",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "medium",
    "tableSize": "N/A",
    "tags": [
      "central",
      "ruins",
      "peaceful"
    ],
    "openingHours": "24/7",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Sunny mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 6.5,
    "image": ""
  },
  {
    "id": 76,
    "name": "The Downs",
    "type": "Nature/Greenery",
    "category": "Nature/Greenery",
    "neighborhood": "Clifton",
    "address": "Clifton Down, Bristol BS8 3NB",
    "lat": 51.462,
    "lng": -2.625,
    "website": "",
    "atmosphere": "Vast open grassland above the Avon Gorge with spectacular views. Popular with students for outdoor study and relaxation.",
    "wifi": "no",
    "plugSockets": "no",
    "noiseLevel": 1,
    "lightingQuality": "excellent",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "N/A",
    "tags": [
      "vast",
      "gorge views",
      "open air"
    ],
    "openingHours": "24/7",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Sunny afternoons",
    "peakBusyTimes": "Weekends",
    "studyScore": 6.8,
    "image": ""
  },
  {
    "id": 77,
    "name": "St Andrew's Churchyard",
    "type": "Nature/Greenery",
    "category": "Nature/Greenery",
    "neighborhood": "Old City",
    "address": "St Andrew's Road, Bristol BS6 5BX",
    "lat": 51.457,
    "lng": -2.598,
    "website": "",
    "atmosphere": "Hidden churchyard garden with benches and mature trees. A peaceful oasis in the city centre.",
    "wifi": "no",
    "plugSockets": "no",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "N/A",
    "tags": [
      "hidden",
      "garden",
      "peaceful oasis"
    ],
    "openingHours": "Dawn to dusk",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Sunny afternoons",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.2,
    "image": ""
  },
  {
    "id": 78,
    "name": "Greville Smyth Park",
    "type": "Nature/Greenery",
    "category": "Nature/Greenery",
    "neighborhood": "Southville",
    "address": "Greville Smyth Park, Ashton Road, Bristol BS3 2EQ",
    "lat": 51.442,
    "lng": -2.606,
    "website": "",
    "atmosphere": "Quiet neighbourhood park in Southville with mature trees and a community garden. Good for outdoor reading.",
    "wifi": "no",
    "plugSockets": "no",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "N/A",
    "tags": [
      "neighbourhood",
      "community garden",
      "quiet"
    ],
    "openingHours": "Dawn to dusk",
    "priceLevel": "Free",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Sunny afternoons",
    "peakBusyTimes": "Weekends",
    "studyScore": 6.5,
    "image": ""
  },
  {
    "id": 79,
    "name": "The Crafty Egg Bedminster",
    "type": "Late-Night Cafe",
    "category": "Late-Night Cafe",
    "neighborhood": "Bedminster",
    "address": "203-207 Church Road, Bedminster, Bristol BS3 2AE",
    "lat": 51.4405,
    "lng": -2.592,
    "website": "https://www.thecraftyegg.co.uk",
    "atmosphere": "All-day brunch cafe that stays open late. Relaxed evening atmosphere with cocktails and comfort food.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "warm",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "late night",
      "brunch",
      "cocktails"
    ],
    "openingHours": "Mon-Sun 8:30am-10pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Evenings",
    "peakBusyTimes": "Weekend brunch",
    "studyScore": 7.0,
    "image": ""
  },
  {
    "id": 80,
    "name": "Kongs of King Street",
    "type": "Late-Night Cafe",
    "category": "Late-Night Cafe",
    "neighborhood": "Old City",
    "address": "King Street, Bristol BS1 4DZ",
    "lat": 51.451,
    "lng": -2.595,
    "website": "",
    "atmosphere": "Retro arcade bar with craft beer and late-night vibes. Not traditional study but great for casual evening work.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 4,
    "lightingQuality": "dim",
    "seatingComfort": "good",
    "laptopFriendly": "limited",
    "crowdLevel": "high",
    "tableSize": "small",
    "tags": [
      "arcade",
      "retro",
      "late night"
    ],
    "openingHours": "Mon-Thu 4pm-12am, Fri-Sat 12pm-2am, Sun 12pm-11pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "N/A",
    "bestTimeStudy": "Weekday evenings",
    "peakBusyTimes": "Friday/Saturday nights",
    "studyScore": 5.5,
    "image": ""
  },
  {
    "id": 81,
    "name": "Spike Island Cafe",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Harbourside",
    "address": "133 Cumberland Road, Bristol BS1 6UX",
    "lat": 51.4475,
    "lng": -2.601,
    "website": "https://www.spikeisland.org.uk",
    "atmosphere": "Arts centre cafe in a converted warehouse on the harbour. Exhibitions, studios, and a creative community.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "arts centre",
      "warehouse",
      "creative"
    ],
    "openingHours": "Tue-Sun 10am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Exhibition openings",
    "studyScore": 8.4,
    "image": ""
  },
  {
    "id": 82,
    "name": "The Grain Barge",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Harbourside",
    "address": "Mardyke Wharf, Hotwell Road, Bristol BS8 4RU",
    "lat": 51.449,
    "lng": -2.61,
    "website": "https://grainbarge.com",
    "atmosphere": "Converted barge on the harbour serving as a pub-cafe. Unique floating venue with harbour views.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "limited",
    "crowdLevel": "medium",
    "tableSize": "small",
    "tags": [
      "barge",
      "floating",
      "harbour"
    ],
    "openingHours": "Mon-Thu 12pm-11pm, Fri-Sat 12pm-12am, Sun 12pm-10:30pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Evenings",
    "studyScore": 6.8,
    "image": ""
  },
  {
    "id": 83,
    "name": "Wardrobe Theatre Cafe",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Old Market",
    "address": "25 West Street, Old Market, Bristol BS2 0DF",
    "lat": 51.4548,
    "lng": -2.5875,
    "website": "https://thewardrobetheatre.com",
    "atmosphere": "Theatre cafe with a bohemian atmosphere. Daytime is quiet and perfect for creative work.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "warm",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "theatre",
      "bohemian",
      "creative"
    ],
    "openingHours": "Mon-Sat 10am-late",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday daytime",
    "peakBusyTimes": "Show nights",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 84,
    "name": "Storysmith",
    "type": "Quiet Study Cafe",
    "category": "Bookstore Cafe",
    "neighborhood": "Harbourside",
    "address": "1 Cargo, Wapping Wharf, Bristol BS1 6WP",
    "lat": 51.4462,
    "lng": -2.5985,
    "website": "https://storysmithbooks.com",
    "atmosphere": "Independent bookshop-cafe at Wapping Wharf. Browse books while enjoying coffee with harbour views.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "bookshop",
      "harbour",
      "independent"
    ],
    "openingHours": "Mon-Sat 9am-6pm, Sun 10am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Weekends",
    "studyScore": 8.3,
    "image": ""
  },
  {
    "id": 85,
    "name": "Emmeline",
    "type": "Quiet Study Cafe",
    "category": "Aesthetic Cafe",
    "neighborhood": "Redland",
    "address": "4 Chandos Road, Redland, Bristol BS6 6PG",
    "lat": 51.4652,
    "lng": -2.6048,
    "website": "",
    "atmosphere": "Beautiful neighbourhood cafe with a focus on sustainability. Bright, plant-filled interior.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "sustainable",
      "plant-filled",
      "bright"
    ],
    "openingHours": "Mon-Sat 8am-4pm, Sun 9am-3pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 8.5,
    "image": ""
  },
  {
    "id": 86,
    "name": "Tradewind Espresso",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Clifton",
    "address": "Regent Street, Clifton, Bristol BS8 4HW",
    "lat": 51.4558,
    "lng": -2.6152,
    "website": "",
    "atmosphere": "Tiny specialty coffee shop in Clifton. Exceptional espresso and a focused, quiet atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 1,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "limited",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "specialty",
      "espresso",
      "tiny"
    ],
    "openingHours": "Mon-Fri 8am-4pm, Sat 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Morning rush",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 87,
    "name": "Redpoint Climbing Centre Cafe",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Brislington",
    "address": "28 Winterstoke Road, Bristol BS3 2NR",
    "lat": 51.438,
    "lng": -2.592,
    "website": "https://www.redpointbristol.co.uk",
    "atmosphere": "Climbing centre cafe with a surprisingly good study atmosphere. Watch climbers while you work.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "large",
    "tags": [
      "climbing",
      "unique",
      "active"
    ],
    "openingHours": "Mon-Fri 7am-10pm, Sat-Sun 9am-8pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Evenings",
    "studyScore": 7.0,
    "image": ""
  },
  {
    "id": 88,
    "name": "Arnos Manor Hotel Lounge",
    "type": "Hotel Lounge",
    "category": "Hotel Lounge",
    "neighborhood": "Brislington",
    "address": "470 Bath Road, Brislington, Bristol BS4 3HQ",
    "lat": 51.438,
    "lng": -2.56,
    "website": "",
    "atmosphere": "Gothic Victorian hotel with atmospheric lounges. Unique setting for quiet study in historic surroundings.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 1,
    "lightingQuality": "warm",
    "seatingComfort": "excellent",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "gothic",
      "victorian",
      "atmospheric"
    ],
    "openingHours": "All day",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Evenings",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 89,
    "name": "Tincan Coffee",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Stokes Croft",
    "address": "Unit 12, Stokes Croft, Bristol BS1 3PY",
    "lat": 51.4608,
    "lng": -2.5895,
    "website": "https://tincancoffee.co.uk",
    "atmosphere": "Specialty coffee roasters with a small cafe space. Exceptional coffee in a no-frills setting.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "roasters",
      "specialty",
      "no-frills"
    ],
    "openingHours": "Mon-Fri 8am-5pm, Sat 9am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Morning rush",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 90,
    "name": "Small Street Espresso",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Old City",
    "address": "21 Small Street, Bristol BS1 1DW",
    "lat": 51.454,
    "lng": -2.5945,
    "website": "",
    "atmosphere": "Compact specialty coffee bar in the Old City. Standing room and a few seats, but excellent coffee.",
    "wifi": "yes",
    "plugSockets": "no",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "medium",
    "tableSize": "small",
    "tags": [
      "espresso bar",
      "compact",
      "old city"
    ],
    "openingHours": "Mon-Fri 7:30am-4pm, Sat 9am-4pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Morning rush",
    "studyScore": 6.5,
    "image": ""
  },
  {
    "id": 91,
    "name": "Hart's Bakery",
    "type": "Quiet Study Cafe",
    "category": "Bakery/Patisserie",
    "neighborhood": "Temple Meads",
    "address": "Arch 35, Lower Approach Road, Bristol BS1 6QS",
    "lat": 51.4488,
    "lng": -2.5825,
    "website": "https://hartsbakery.co.uk",
    "atmosphere": "Award-winning bakery in a railway arch near Temple Meads. Incredible sourdough, pastries, and a bustling morning atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "high",
    "tableSize": "medium",
    "tags": [
      "award-winning",
      "railway arch",
      "sourdough"
    ],
    "openingHours": "Mon-Fri 8am-5pm, Sat 8am-4pm, Sun 10am-3pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Morning rush",
    "studyScore": 7.2,
    "image": ""
  },
  {
    "id": 92,
    "name": "Ahh Toots Totterdown",
    "type": "Quiet Study Cafe",
    "category": "Hidden Gem",
    "neighborhood": "Totterdown",
    "address": "54 Wells Road, Totterdown, Bristol BS4 2AG",
    "lat": 51.4398,
    "lng": -2.5828,
    "website": "",
    "atmosphere": "Vintage cafe in colourful Totterdown. Homemade cakes, friendly staff, and a warm community atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "warm",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "small",
    "tags": [
      "vintage",
      "totterdown",
      "homemade"
    ],
    "openingHours": "Mon-Sat 9am-5pm, Sun 10am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 93,
    "name": "Bristolian Cafe",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Montpelier",
    "address": "2 Picton Street, Montpelier, Bristol BS6 5QA",
    "lat": 51.462,
    "lng": -2.585,
    "website": "",
    "atmosphere": "Classic greasy spoon turned hipster cafe in Montpelier. Affordable, generous, and authentically Bristol.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "classic",
      "affordable",
      "authentic"
    ],
    "openingHours": "Mon-Fri 8am-3pm, Sat 9am-3pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 7.0,
    "image": ""
  },
  {
    "id": 94,
    "name": "Wapping Wharf Container Yard",
    "type": "Quiet Study Cafe",
    "category": "Creative Workspace",
    "neighborhood": "Wapping Wharf",
    "address": "Gaol Ferry Steps, Wapping Wharf, Bristol BS1 6WE",
    "lat": 51.4468,
    "lng": -2.5982,
    "website": "",
    "atmosphere": "Shipping container food court by the harbour. Multiple food vendors, outdoor seating, and a vibrant atmosphere.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "basic",
    "laptopFriendly": "limited",
    "crowdLevel": "high",
    "tableSize": "medium",
    "tags": [
      "containers",
      "harbour",
      "food court"
    ],
    "openingHours": "Mon-Sun 10am-10pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Lunch and evenings",
    "studyScore": 6.0,
    "image": ""
  },
  {
    "id": 95,
    "name": "Bristolian Cafe & Bar",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Henleaze",
    "address": "Henleaze Road, Henleaze, Bristol BS9 4HG",
    "lat": 51.48,
    "lng": -2.604,
    "website": "",
    "atmosphere": "Suburban cafe in leafy Henleaze. Quiet, spacious, and popular with local residents.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "suburban",
      "quiet",
      "spacious"
    ],
    "openingHours": "Mon-Sat 8am-5pm, Sun 9am-4pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 96,
    "name": "Alchemy 198",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Gloucester Road",
    "address": "198 Gloucester Road, Bristol BS7 8NU",
    "lat": 51.471,
    "lng": -2.5912,
    "website": "",
    "atmosphere": "Specialty coffee shop on Gloucester Road with a focus on quality. Bright, modern interior.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "specialty",
      "gloucester road",
      "modern"
    ],
    "openingHours": "Mon-Fri 7:30am-5pm, Sat-Sun 8:30am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "excellent",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "Weekend mornings",
    "studyScore": 8.0,
    "image": ""
  },
  {
    "id": 97,
    "name": "Caf\u00e9 Grounded",
    "type": "Quiet Study Cafe",
    "category": "Quiet Study Cafe",
    "neighborhood": "Bishopston",
    "address": "Gloucester Road, Bishopston, Bristol BS7 8TZ",
    "lat": 51.4735,
    "lng": -2.5922,
    "website": "",
    "atmosphere": "Community cafe with a focus on mental health and wellbeing. Warm, inclusive atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "low",
    "tableSize": "medium",
    "tags": [
      "wellbeing",
      "community",
      "inclusive"
    ],
    "openingHours": "Mon-Sat 9am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "All day",
    "peakBusyTimes": "Lunch hour",
    "studyScore": 8.2,
    "image": ""
  },
  {
    "id": 98,
    "name": "M Shed Cafe",
    "type": "Quiet Study Cafe",
    "category": "Museum/Gallery Cafe",
    "neighborhood": "Harbourside",
    "address": "Princes Wharf, Wapping Road, Bristol BS1 4RN",
    "lat": 51.4485,
    "lng": -2.5965,
    "website": "https://www.bristolmuseums.org.uk/m-shed",
    "atmosphere": "Museum cafe with harbour views and Bristol history exhibitions. Bright, spacious, and educational.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 2,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "museum",
      "harbour",
      "educational"
    ],
    "openingHours": "Tue-Sun 10am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "School holidays",
    "studyScore": 7.8,
    "image": ""
  },
  {
    "id": 99,
    "name": "Bristol Museum & Art Gallery Cafe",
    "type": "Quiet Study Cafe",
    "category": "Museum/Gallery Cafe",
    "neighborhood": "Park Street",
    "address": "Queens Road, Clifton, Bristol BS8 1RL",
    "lat": 51.4558,
    "lng": -2.6042,
    "website": "https://www.bristolmuseums.org.uk/bristol-museum-and-art-gallery",
    "atmosphere": "Grand Victorian museum with a lovely cafe. Surrounded by art and natural history collections.",
    "wifi": "yes",
    "plugSockets": "limited",
    "noiseLevel": 2,
    "lightingQuality": "good",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "medium",
    "tags": [
      "museum",
      "victorian",
      "art"
    ],
    "openingHours": "Tue-Sun 10am-5pm",
    "priceLevel": "\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday afternoons",
    "peakBusyTimes": "School holidays",
    "studyScore": 7.5,
    "image": ""
  },
  {
    "id": 100,
    "name": "We The Curious Cafe",
    "type": "Quiet Study Cafe",
    "category": "Museum/Gallery Cafe",
    "neighborhood": "Harbourside",
    "address": "One Millennium Square, Bristol BS1 5DB",
    "lat": 51.4505,
    "lng": -2.6,
    "website": "https://www.wethecurious.org",
    "atmosphere": "Science centre cafe with interactive exhibits nearby. Modern, bright space with a curious atmosphere.",
    "wifi": "yes",
    "plugSockets": "yes",
    "noiseLevel": 3,
    "lightingQuality": "excellent",
    "seatingComfort": "good",
    "laptopFriendly": "yes",
    "crowdLevel": "medium",
    "tableSize": "large",
    "tags": [
      "science",
      "interactive",
      "modern"
    ],
    "openingHours": "Mon-Sun 10am-5pm",
    "priceLevel": "\u00a3\u00a3",
    "coffeeQuality": "good",
    "bestTimeStudy": "Weekday mornings",
    "peakBusyTimes": "School holidays",
    "studyScore": 7.0,
    "image": ""
  }
];
