CREATE TABLE `community_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`submittedBy` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`category` varchar(100) NOT NULL,
	`neighborhood` varchar(100) NOT NULL,
	`address` text NOT NULL,
	`lat` decimal(10,7) NOT NULL,
	`lng` decimal(10,7) NOT NULL,
	`website` varchar(500),
	`priceLevel` varchar(20) NOT NULL,
	`atmosphere` text,
	`noiseLevel` int NOT NULL,
	`wifiQuality` int NOT NULL,
	`lightingQuality` int NOT NULL,
	`seatingComfort` int NOT NULL,
	`laptopFriendly` int NOT NULL,
	`crowdLevel` int NOT NULL,
	`studyScore` decimal(3,1) NOT NULL,
	`tags` text NOT NULL,
	`images` text NOT NULL,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'approved',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `community_submissions_id` PRIMARY KEY(`id`)
);
